version: "3"

services:
  app:
    build: .
    # entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3333:3333
      - 5555:5555
    volumes:
      - .:/usr/src/app
    links:
      - db
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres
    container_name: prisma_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=prisma
    volumes:
      - ./.docker/pgdata:/data/postgres
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
